version: "3.7"

services:
  a:
    container_name: task-a
    image: "node:21-alpine"
    working_dir: /usr/src/example
    environment:
      CHUNK_NAME: a
      PORT: 3000
    volumes:
    - ../:/usr/src
    command: ["npm", "start"]
    networks:
      - webservice_splitter_network
  b:
    container_name: task-b
    image: "node:21-alpine"
    working_dir: /usr/src/example
    environment:
      CHUNK_NAME: b
      PORT: 3000
    volumes:
    - ../:/usr/src
    command: ["npm", "start"]
    networks:
      - webservice_splitter_network
  c:
    container_name: task-c
    image: "node:21-alpine"
    working_dir: /usr/src/example
    environment:
      CHUNK_NAME: c
      PORT: 3000
    volumes:
    - ../:/usr/src
    command: ["npm", "start"]
    networks:
      - webservice_splitter_network

networks:
  webservice_splitter_network:
