services:
  a:
    container_name: task-a
    image: "node:21-alpine"
    working_dir: /usr/src/examples/custom-transport
    environment:
      CHUNK_NAME: a
      PORT: 3000
    volumes:
    - ../..:/usr/src
    - ../basic:/usr/src/examples/custom-transport
    - ./api/api-config.json:/usr/src/examples/custom-transport/api/api-config.json
    - ./json-rpc-transport:/usr/src/examples/custom-transport/json-rpc-transport
    - ./package.json:/usr/src/examples/custom-transport/package.json
    - ./node_modules:/usr/src/examples/custom-transport/node_modules
    command: ["npm", "start"]
    networks:
      - webservice_splitter_network
  b:
    container_name: task-b
    image: "node:21-alpine"
    working_dir: /usr/src/examples/custom-transport
    environment:
      CHUNK_NAME: b
      PORT: 3000
    volumes:
    - ../..:/usr/src
    - ../basic:/usr/src/examples/custom-transport
    - ./api/api-config.json:/usr/src/examples/custom-transport/api/api-config.json
    - ./json-rpc-transport:/usr/src/examples/custom-transport/json-rpc-transport
    - ./package.json:/usr/src/examples/custom-transport/package.json
    - ./node_modules:/usr/src/examples/custom-transport/node_modules
    command: ["npm", "start"]
    networks:
      - webservice_splitter_network
  c:
    container_name: task-c
    image: "node:21-alpine"
    working_dir: /usr/src/examples/custom-transport
    environment:
      CHUNK_NAME: c
      PORT: 3000
    volumes:
    - ../..:/usr/src
    - ../basic:/usr/src/examples/custom-transport
    - ./api/api-config.json:/usr/src/examples/custom-transport/api/api-config.json
    - ./json-rpc-transport:/usr/src/examples/custom-transport/json-rpc-transport
    - ./package.json:/usr/src/examples/custom-transport/package.json
    - ./node_modules:/usr/src/examples/custom-transport/node_modules
    command: ["npm", "start"]
    networks:
      - webservice_splitter_network

networks:
  webservice_splitter_network:
